"""add annotation to positions

Revision ID: 24048a0e2890
Revises: 4e9fc46b3a13
Create Date: 2026-07-13 09:14:33.874283

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24048a0e2890"
down_revision: str | None = "4e9fc46b3a13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("positions", sa.Column("annotation", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("positions", "annotation")
    # ### end Alembic commands ###
